title: The first page
author: Vienna Yang
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This page is to represent what the file is. But, I don't know what to write. So,just like this.
  THE END
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
